### ISSUE TITLE
Investigate deployment failures

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest-forked#17]
Although the package has been deployed, the job that did manage the deploy failed strangely:

https://travis-ci.org/pytest-dev/pytest-forked/builds/493316392?utm_source=github_status&utm_medium=notification

We probably should update the configuration to use stages as well.

**Comment by rmcdiffett** [comment]
@nicoddemus We (my company) have noticed a failure in being able to download this project via an Artifactory virtual project since your latest release (1.0.2) today.  We have had to pin our dependencies back to 1.0.1.  Error is that it throws an "Unknown content length".

**Comment by nicoddemus** [comment]
Hi @rmcdiffett,

Hmm strange, I just installed the 1.0.2 package into a fresh virtual environment and it worked perfectly. Also I manually downloaded the package and checked that it appears to be fine. Can you verify your artifactory repo? Perhaps manually downloading the file and ensuring it can be extracted?

**Comment by webknjaz** [comment]
@nicoddemus maybe you need `skip-cleanup` in travis config? https://travis-ci.org/pytest-dev/pytest-forked/jobs/493316393#L607

**Comment by rmcdiffett** [comment]
> Hi @rmcdiffett,
> 
> Hmm strange, I just installed the 1.0.2 package into a fresh virtual environment and it worked perfectly. Also I manually downloaded the package and checked that it appears to be fine. Can you verify your artifactory repo? Perhaps manually downloading the file and ensuring it can be extracted?

This issue self-corrected with no intervention on our side.  Thank you!

**Comment by webknjaz** [comment]
> We probably should update the configuration to use stages as well.

Implemented via https://github.com/pytest-dev/pytest-forked/pull/40.
Looks like no further action is needed. Also, @rmcdiffett's problem looks more or less like a caching issue (PyPI cache usually gets updated during 10 minutes after publishing a release).
