### ISSUE TITLE
Display test name before running it

### ISSUE THREAD

**Issue by jhagege** [pytest-dev/pytest-forked#29]
Hi, I am sometimes having a hard time troubleshooting failing tests stuck in an infinite loop. 
The reason is that output is being printed only if test finished (fail or success), but if it is stuck, then it is very hard to identify which test is stuck.
Could you please suggest a pattern to print the test name to STDOUT / STDERR (on a CI server for example) before running any test ? 
Thanks much.

**Comment by jhagege** [comment]
Also, are you aware of anny pattern to retrieve logs from an ongoing test (stuck test for example) ?

**Comment by antoniovs1029** [comment]
I was having this exact same problem of your original question, and simply using `pytest -v` is enough to output the name of each test before it runs on my CI output.

About the second question, I wouldn't know as I'm not very familiar with pytest, but seems that `pytest -s` stops pytest from capturing the stdout, and so I think that should make it possible to output the log directly on your standard output while the log is running.
