### ISSUE TITLE
`pytest_runtest_logstart` and `pytest_runtest_logfinish` are not in effect

### ISSUE THREAD

**Issue by wy-z** [pytest-dev/pytest-forked#31]
`pytest-forked` reimplemented `pytest_runtest_protocol`, but `pytest_runtest_logstart` and `pytest_runtest_logfinish` were ignored.

Here are the codes in `pytest-forked` and `pytest`:
https://github.com/pytest-dev/pytest-forked/blob/bedbc83b139deede2aa90257e234749561600cc9/src/pytest_forked/__init__.py#L40-L45
https://github.com/pytest-dev/pytest/blob/259e5d0610202453f9beace6cab336b11d4353a9/src/_pytest/runner.py#L87
![image](https://user-images.githubusercontent.com/4213483/80582514-6e85ef00-8a41-11ea-9736-0fd2d2beb41e.png)

**Comment by wy-z** [comment]
How about implementing `pytest_runtest_logstart` and `pytest_runtest_logfinish` in `pytest_runtestloop` instead of in `pytest_runtest_protocol`? @nicoddemus 
https://github.com/pytest-dev/pytest/blob/4f8fff9cab6e2333890e21eb840724e7e4d41763/src/_pytest/main.py#L260-L277
![image](https://user-images.githubusercontent.com/4213483/80585087-4ac4a800-8a45-11ea-814c-a7276d4fa136.png)

**Comment by webknjaz** [comment]
@wy-z this library is in maintenance mode. It is unlikely that the maintainers will implement your request but if you want to send a PR — feel free. Just make sure that it's well-covered by tests.
