### ISSUE TITLE
v1.3.0 not available on conda-forge

### ISSUE THREAD

**Issue by luk-f-a** [pytest-dev/pytest-forked#50]
hi, I saw the warning that maintenance is down to bare minimum but I was wondering about the process for conda-forge builds. I cannot find v1.3.0 on conda-forge, but I don't know what's required to have that build.

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus did you provide the conda firge build or was it a random 3rd party?

I never did a conda build for this

**Comment by nicoddemus** [comment]
Sorry, I must have missed the notification. 

https://github.com/conda-forge/pytest-forked-feedstock/pull/9

Should be up in an hour or so. 👍
