### ISSUE TITLE
Alternative to fork in Windows

### ISSUE THREAD

**Issue by Astlaan** [pytest-dev/pytest-forked#56]
Hi. 

I understand that the forking functionality is not supported in windows.
Is there however any other way package capable of running the different test functions in different processes?

My code is something like:

```
# test_scripts.py

scripts = [ ... ]   #list of filepaths

@pytest.mark.parametrize('script', scripts)
def test_script_execution(script):
    runpy.run_path(script)
```

The scripts don't need any variables or state from this process (so I don't exactly need to fork), but they do need to be run in different processes, since they use packages containing global variables.

Is there any way to use pytest for this in windows?

**Comment by RonnyPfannschmidt** [comment]
At that point why not just run the actual subprocess?

**Comment by Astlaan** [comment]
Turns out that pytest-xdist -n parameter works well for my needs.

Thanks
