### ISSUE TITLE
py==1.11.0 vulnerability

### ISSUE THREAD

**Issue by thebaptiste** [pytest-dev/pytest-forked#80]
Hello

It would be great to remove the dependency on the py library which  is no longer maintained anymore and has security issue : 

See https://github.com/pytest-dev/py/issues/287

Regards

**Comment by webknjaz** [comment]
Who said that it's not maintained? The description there literally says "maintenance mode".
Also, can you explain in what way it can realistically be harmful to this plugin?

**Comment by thebaptiste** [comment]
You are right, I'm wrong, I must have confused with another repository.
I don't know if this security issue will be fixed in py but I don't know either if it's harmful for pytest-forked.
Sorry, you can close.

**Comment by nicoddemus** [comment]
Thanks @thebaptiste,

That security vulnerability does not apply to pytest-fork, as it does not use `py.svn`.

However it is certainly in our interest to remove the dependency to `py`. :+1:
